<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>SharpWifiManager</PackageId>
    <Authors>Luca</Authors>
    <Company>dima.91</Company>
    <Description>C# library to manage wifi connection using Linux D-Bus.</Description>
    <PackageProjectUrl>https://github.com/dima91/sharp-wifi-manager</PackageProjectUrl>
    <RepositoryUrl>https://github.com/dima91/sharp-wifi-manager</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
